# Minimal Jekyll Configuration for ShokaX Theme
title: "Kim Gabe's DS Blog"
description: "Data Science Blog with ShokaX Theme"
baseurl: ""
url: "http://localhost:4000"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Basic settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
timezone: Asia/Seoul

# Plugins (minimal)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author
author:
  name: "Kim Gabe"
  bio: "Data Scientist & Full-Stack Developer"

# Pagination
paginate: 5
paginate_path: /page:num/

# Exclude from processing
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true 